### ISSUE TITLE
`MSVBVM60.DLL` is unavailable in the repository, yet when it's present, it allows the widget to run on Linux perfectly.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [yereverluvinunclebert/Panzer-Earth-gauge-VB6#1]
#### **Information**

<table>
<tbody>
<tr>
<th>
Commit ID
</th>
<td>

`d975e30b8daa17e1ae752475ec1eaf72a2b6522a`

</td>
</tr>
<tr>
<th>
Cloned to
</th>
<td>

<a href="file:///home/rokejulianlockhart/Panzer-Earth-gauge-VB6/"><code>/home/rokejulianlockhart/Panzer-Earth-gauge-VB6/</code></a>, using [`v1.3.0/Gittyup.flatpak`](https://github.com/Murmele/Gittyup/releases/download/gittyup_v1.3.0/Gittyup.flatpak)

</td>
</tr>
</tbody>
</table>

#### **Errata**
	
1.	Installation supposedly succeeds:

	![image](https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/assets/42837531/82b91bb5-12c0-4c08-95f6-73b6132d218d)

1.	Documentation appears:

	![image](https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/assets/42837531/23149637-e4e4-4363-a961-ccaf3f3489e4)

1.	However, the binary cannot run due to unavailable dependencies:

	#### **Logs**

	<blockquote>

	```dart
	0248:err:module:import_dll Library MSVBVM60.DLL (which is needed by L"Z:\\home\\rokejulianlockhart\\Panzer-Earth-gauge-VB6\\Panzer Earth Gauge.exe") not found
	0248:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\rokejulianlockhart\\Panzer-Earth-gauge-VB6\\Panzer Earth Gauge.exe" failed, status c0000135
	```

	</blockquote>

	#### **Error Window**

	![image](https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/assets/42837531/37c4defa-0c74-4f71-a4cc-6500902638aa)

#### **Diagnosis**

1. Download [`dll.website/download/msvbvm60_dll_417e414c57cd55fdee5f0bdcf331c967.zip`](https://dll.website/download/msvbvm60_dll_417e414c57cd55fdee5f0bdcf331c967.zip) (from [`dll.website/msvbvm60-dll`](https://dll.website/msvbvm60-dll)).
	
	Designated as clean by [`virustotal.com/gui/file-analysis/MDNhODQxM2IyNWJjNjQxYTk3ZWZiNmUxZjFmMmNiMmY6MTY4ODEzNzI3OQ==/detection`](https://www.virustotal.com/gui/file-analysis/MDNhODQxM2IyNWJjNjQxYTk3ZWZiNmUxZjFmMmNiMmY6MTY4ODEzNzI3OQ==/detection).

1. Extract [`/home/rokejulianlockhart/Panzer-Earth-gauge-VB6/msvbvm60_dll_417e414c57cd55fdee5f0bdcf331c967.zip`](file:///home/rokejulianlockhart/Panzer-Earth-gauge-VB6/msvbvm60_dll_417e414c57cd55fdee5f0bdcf331c967.zip) into [`/home/rokejulianlockhart/Panzer-Earth-gauge-VB6/msvbvm60.dll`](file:///home/rokejulianlockhart/Panzer-Earth-gauge-VB6/msvbvm60.dll)

	> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/pull/2#issue-1782702937

	![image](https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/assets/42837531/4ae7f660-ffdc-4d7b-8a77-3ecde22335da)

**Comment by yereverluvinunclebert** [comment]
Very good testing indeed. Unfortunately I will not be bundling dedicated o/s files from Microsoft with my application. Not sensible to do so. Don't want to be sued by Microsoft and also it is a tadge impractical. However, I might add a note in the help file to assist future Linux users. The same also applies to ReactOS users as the same file is not present in ReactOS, coming only from Microsoft oses.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues/1#issuecomment-1622075944

Yeah, @yereverluvinunclebert, they should be standard in < [`gitlab.winehq.org/wine/wine/-/wikis/Source-Code?version_id=93f6e14f2247d7f9804678b5b4876ac3418740dd`](https://gitlab.winehq.org/wine/wine/-/wikis/Source-Code?version_id=93f6e14f2247d7f9804678b5b4876ac3418740dd).

**Comment by roke-julian-lockhart** [comment]
> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues/1#event-9733768706

@yereverluvinunclebert, probably worth closing this as not planned rather than [`reason%3Acompleted`](https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues?q=is%3Aissue+is%3Aclosed+reason%3Acompleted).

**Comment by roke-julian-lockhart** [comment]
> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues/1#issuecomment-1622146452

@yereverluvinunclebert, this has been filed at [`bugs.winehq.org/show_bug.cgi?id=19816#c0`](https://bugs.winehq.org/show_bug.cgi?id=19816#c0:~:text=Multiple%20games%20and-,applications%20need%20'msvbvm60.dll'%20('winetricks%20vb6run'%20is%20a%20workaround),-First%20Last%20Prev).

**Comment by yereverluvinunclebert** [comment]
Forthcoming TwinBasic versions may not need the DLL at all.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues/1#issuecomment-2506167057

@yereverluvinunclebert, https://github.com/twinbasic/twinbasic/issues/360?ref=nolongerset.com#event-9651265040 is complete, so perhaps it's already no longer needed?
