### ISSUE TITLE
Linux screenshot needed.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [yereverluvinunclebert/Panzer-Earth-gauge-VB6#6]
Per request by @yereverluvinunclebert.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues/6#issue-1810924545

@yereverluvinunclebert, I've taken one:

![image](https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/assets/42837531/d9737244-e3cb-49cb-9565-62d40fe75340)

Apologies for the wait. Turns out, per [`discuss.kde.org/t/3030/2`](https://discuss.kde.org/t/how-to-disable-specific-window-rule-preset/3030/2?u=rokejulianlockhart), that a surprising amount of work was needed to get this done. However, I can now pump out screenshots willy-nilly if need be.

**Comment by yereverluvinunclebert** [comment]
Perfect, now one without the about image please Roke.
Hurry up!

**Comment by roke-julian-lockhart** [comment]
> https://github.com/yereverluvinunclebert/Panzer-Earth-gauge-VB6/issues/6#issuecomment-1642149669

@yereverluvinunclebert, I've posted one to [`imgur.com/YXheYmD`](https://imgur.com/YXheYmD):

> ![image](https://i.imgur.com/YXheYmD.png)

The rest are at [`imgur.com/a/YEIr6is`](https://imgur.com/a/YEIr6is).

**Comment by yereverluvinunclebert** [comment]
See https://reactos.org/forum/viewtopic.php?p=147553#p147553
